# Generated by Django 5.1 on 2024-10-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taks', '0003_advance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advance',
        ),
    ]
