# Generated by Django 5.1 on 2024-10-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taks', '0007_task_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pdf_file',
        ),
    ]
