# Generated by Django 5.1 on 2024-10-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taks', '0008_remove_task_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('WRK', 'Trabajo'), ('STD', 'Estudio'), ('PER', 'Personal'), ('OTH', 'Otro')], default='OTH', max_length=3),
        ),
    ]
